USE [master]
GO

/****** Object:  Database [laundry_manager]    Script Date: 10/16/2020 2:07:21 PM ******/
CREATE DATABASE [laundry_manager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'laundry_manager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\laundry_manager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'laundry_manager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\laundry_manager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [laundry_manager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [laundry_manager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [laundry_manager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [laundry_manager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [laundry_manager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [laundry_manager] SET ARITHABORT OFF 
GO

ALTER DATABASE [laundry_manager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [laundry_manager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [laundry_manager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [laundry_manager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [laundry_manager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [laundry_manager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [laundry_manager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [laundry_manager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [laundry_manager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [laundry_manager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [laundry_manager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [laundry_manager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [laundry_manager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [laundry_manager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [laundry_manager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [laundry_manager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [laundry_manager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [laundry_manager] SET RECOVERY FULL 
GO

ALTER DATABASE [laundry_manager] SET  MULTI_USER 
GO

ALTER DATABASE [laundry_manager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [laundry_manager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [laundry_manager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [laundry_manager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [laundry_manager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [laundry_manager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [laundry_manager] SET  READ_WRITE 
GO

